spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payandwithdraw?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
  freemarker:
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    suffix: .html
    charset: UTF-8
    templateLoaderPath: classpath:/templates/
  redis:
      host: 127.0.0.1
      port: 6379
      database: 0 # 设置数据库索引为0 默认为0
      password: # 密码为空
      jedis:
          pool:
              max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
              max-idle: 10 # 连接池中的最大空闲连接
              min-idle: 2 # 连接池中的最小空闲连接
mybatis:
  config-location: classpath:mybatis-config.xml
server:
  port: 8081
