spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payandwithdraw?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
  freemarker:
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    suffix: .html
    charset: UTF-8
    templateLoaderPath: classpath:/templates/
mybatis:
  config-location: classpath:mybatis-config.xml
server:
  port: 8080
